#!/usr/bin/env bash
docker run -it \
      -v "/run/user/$(id -u)/pulse:/run/user/1000/pulse" \
      -v "${HOME}/.config/pulse/cookie:/home/rhasspy/.config/pulse/cookie" \
      -v '/etc/localtime:/etc/localtime:ro' \
      rhasspy/audio-input/pulseaudio \
      "$@"
