#!/usr/bin/env bash
this_dir="$( cd "$( dirname "$0" )" && pwd )"
venv="${this_dir}/.venv"

if [[ ! -d "${venv}" ]]; then
    echo "Virtual environment missing at ${venv}"
    echo "Did you run install.sh?"
    exit 1
fi

if [[ -z "$@" ]]; then
    echo "No command given"
    exit 1
fi

source "${venv}/bin/activate"
export LD_LIBRARY_PATH="${venv}/lib:${LD_LIBRARY_PATH}"

# Gather all the bin paths
rhasspy_paths=("${venv}/bin" "${this_dir}/bin")
rhasspy_paths+=("${this_dir}/intent_recognition/fsticuffs/bin")
rhasspy_paths+=("${this_dir}/speech_to_text/pocketsphinx/bin")
rhasspy_paths+=("${this_dir}/speech_to_text/kaldi/bin")
rhasspy_paths+=("${this_dir}/wake_word/porcupine/bin")
rhasspy_paths+=("${this_dir}/voice_command/webrtcvad/bin")
rhasspy_paths+=("${this_dir}/training/bin")
rhasspy_paths+=("${this_dir}/training/vocab_g2p/bin")

# Convert to colon-delimited string
rhasspy_path=$(IFS=':'; echo "${rhasspy_paths[*]}")
export PATH="${rhasspy_path}:${PATH}"

# Path to command-line parsing library
export shflags="${this_dir}/etc/shflags"

# Path to kaldi
export kaldi_dir="${this_dir}/build/kaldi-master"

# Run command in Rhasspy venv
"$@"
