#!/usr/bin/env bash
set -e
this_dir="$( cd "$( dirname "$0" )" && pwd )"

# -----------------------------------------------------------------------------

# Load virtual environment
venv="${PWD}/.venv"
if [[ ! -d "${venv}" ]]; then
    venv="${this_dir}/.venv"
fi

if [[ -d "${venv}" ]]; then
    source "${venv}/bin/activate"
    export PATH="${venv}/bin:${PATH}"
    export LD_LIBRARY_PATH="${venv}/lib:${LD_LIBRARY_PATH}"
fi

temp_list="$(mktemp)"
function finish {
    rm -f "${temp_list}"
}

trap finish EXIT

# -----------------------------------------------------------------------------

cat > "${temp_list}"
phonetisaurus-apply --word_list "${temp_list}" "$@" | \
    PYTHONPATH="${this_dir}:${PYTHONPATH}" \
    python3 -m vocab_g2p
