#!/usr/bin/env bash

# -----------------------------------------------------------------------------
# Command-line Arguments
# -----------------------------------------------------------------------------

. "${HOME}/shflags"

DEFINE_string 'profile' '' 'Path to profile directory' 'p'

DEFINE_string 'mqtt-host' '127.0.0.1' 'MQTT server address'
DEFINE_integer 'mqtt-port' 1883 'MQTT server port'

DEFINE_string 'play-wav' 'rhasspy/audio-output/play-wav' 'Topic to receive WAV play requests'
DEFINE_string 'wav-played' 'rhasspy/audio-output/wav-played' 'Topic to send after WAV is played'

FLAGS "$@" || exit $?
eval set -- "${FLAGS_ARGV}"

# -----------------------------------------------------------------------------
# Default Settings
# -----------------------------------------------------------------------------

set -e

profile_dir="${FLAGS_profile}"

mqtt_host="${FLAGS_mqtt_host}"
mqtt_port="${FLAGS_mqtt_port}"

play_wav="${FLAGS_play_wav}"
wav_played="${FLAGS_wav_played}"

# -----------------------------------------------------------------------------
# Profile
# -----------------------------------------------------------------------------

if [[ ! -z "${profile_dir}" ]]; then
    profile_yml="${profile_dir}/profile.yml"

    var_file="$(mktemp)"
    export profile_dir

    yq "${profile_yml}" \
       -q mqtt_host 'mqtt.host' "${mqtt_host}" \
       -q mqtt_port 'mqtt.port' "${mqtt_port}" \
       -q play_wav 'audio-output.mqtt-events.play-wav' "${play_wav}" \
       -q wav_played 'audio-output.mqtt-events.wav-played' "${wav_played}" \
       > "${var_file}"

    source "${var_file}"
fi

# -----------------------------------------------------------------------------

topic_file=$(mktemp)
export topic_file

while true;
do
    mosquitto_sub -h "${mqtt_host}" -p "${mqtt_port}" -C 1 -v -N -t "${play_wav}/#" | \
        python3 "${HOME}/filter-topic.py" --topic-file "${topic_file}" | \
        gst-launch-1.0 \
            filesrc location=/dev/stdin ! \
            wavparse ! \
            audioconvert ! \
            audioresample ! \
            pulsesink

    request_id="$(cat "${topic_file}" | sed -e "s|^${play_wav}||")"
    mosquitto_pub -h "${mqtt_host}" -p "${mqtt_port}" -t "${wav_played}${request_id}" -m '{}'
done
