#!/usr/bin/env bash
this_dir="$( cd "$( dirname "$0" )" && pwd )"

# -----------------------------------------------------------------------------
# Command-line Arguments
# -----------------------------------------------------------------------------

. "${this_dir}/etc/shflags"

DEFINE_string 'profile' '' 'Path to profile directory' 'p'

DEFINE_string 'http-host' '0.0.0.0' 'HTTP server address'
DEFINE_integer 'http-port' 8000 'HTTP server port'

# fsticuffs
DEFINE_boolean 'debug' false 'Print DEBUG messages to console'
DEFINE_string 'intent-fst' '' 'Path to intent finite state transducer'

FLAGS "$@" || exit $?
eval set -- "${FLAGS_ARGV}"

# -----------------------------------------------------------------------------
# Default Settings
# -----------------------------------------------------------------------------
set -e

profile_dir="${FLAGS_profile}"

http_host="${FLAGS_http_host}"
http_port="${FLAGS_http_port}"

intent_fst="${FLAGS_intent_fst}"

if [[ "${FLAGS_debug}" -eq "${FLAGS_TRUE}" ]]; then
    debug='--debug'
fi

# -----------------------------------------------------------------------------
# Profile
# -----------------------------------------------------------------------------

if [[ ! -z "${profile_dir}" ]]; then
    var_file="$(mktemp)"
    function finish {
        rm -f "${var_file}"
    }

    trap finish EXIT

    export profile_dir

    # Load virtual environment
    venv="${this_dir}/.venv"
    if [[ -d "${venv}" ]]; then
        source "${venv}/bin/activate"
        export LD_LIBRARY_PATH="${venv}/lib:${LD_LIBRARY_PATH}"
    fi

    python3 "${this_dir}/bin/yq" "${profile_dir}/profile.yml" \
            -q http_host 'intent-recognition.fsticuffs.http-server.host' "${http_host}" \
            -q http_port 'intent-recognition.fsticuffs.http-server.port' "${http_port}" \
            -q intent_fst 'intent-recognition.fsticuffs.intent-fst' "${intent_fst}" \
            > "${var_file}"

    source "${var_file}"
    finish
fi

# -----------------------------------------------------------------------------

args=("${debug}")

if [[ ! -z "${intent_fst}" ]]; then
    args+=('--intent-fst' "${intent_fst}")
fi

args+=("$@")

# -----------------------------------------------------------------------------
# Events FIFO
# -----------------------------------------------------------------------------

events_fifo="$(mktemp -u)"

function finish {
    rm -f "${events_fifo}"
}

trap finish EXIT
mkfifo "${events_fifo}"

# -----------------------------------------------------------------------------

python3 "${this_dir}/fsticuffs/http_server.py" \
        --host "${http_host}" --port "${http_port}" \
        < "${events_fifo}" | \
    "${this_dir}/fsticuffs-cli" "${args[@]}" > "${events_fifo}"
