#!/usr/bin/env bash
set -e
this_dir="$( cd "$( dirname "$0" )" && pwd )"

# -----------------------------------------------------------------------------

# Load virtual environment
venv="${this_dir}/.venv"
if [[ -d "${venv}" ]]; then
    source "${venv}/bin/activate"
    export LD_LIBRARY_PATH="${venv}/lib:${LD_LIBRARY_PATH}"
fi

# -----------------------------------------------------------------------------

export PYTHON_PATH="${this_dir}:${PYTHON_PATH}"

python3 -m fsticuffs "$@"
