version: '2'
services:
  mqtt:
    image: cecep-prime:15555/docker/eclipse-mosquitto
    tty: true
  # wake:
  #   image: rhasspy/wake-word/porcupine
  #   volumes:
  #     - ./profile:/profile
  #   command: --debug --auto-start
  #   tty: true
  # command:
  #   image: rhasspy/voice-detection/webrtcvad
  #   volumes:
  #     - ./profile:/profile
  #   command: --debug
  #   tty: true
  stt:
    image: rhasspy/speech-to-text/pocketsphinx
    volumes:
      - ./profile:/profile
    command: mqtt --profile /profile --debug
    tty: true
  intent:
    image: rhasspy/intent-recognition/fsticuffs
    volumes:
      - ./profile:/profile
    command: mqtt --profile /profile --debug
    tty: true
