#!/usr/bin/env bash

# -----------------------------------------------------------------------------
# Command-line Arguments
# -----------------------------------------------------------------------------

. "/shflags"

DEFINE_string 'profile' '' 'Path to profile directory' 'p'

DEFINE_string 'http-host' '0.0.0.0' 'HTTP server address'
DEFINE_integer 'http-port' 8000 'HTTP server port'

FLAGS "$@" || exit $?
eval set -- "${FLAGS_ARGV}"

# -----------------------------------------------------------------------------
# Default Settings
# -----------------------------------------------------------------------------
set -e

profile_dir="${FLAGS_profile}"

http_host="${FLAGS_http_host}"
http_port="${FLAGS_http_port}"

intent_fst=''

# -----------------------------------------------------------------------------
# Profile
# -----------------------------------------------------------------------------

if [[ ! -z "${profile_dir}" ]]; then
    profile_yml="${profile_dir}/profile.yml"

    var_file="$(mktemp)"
    function finish {
        rm -f "${var_file}"
    }

    trap finish EXIT

    export profile_dir
    yq "${profile_yml}" \
       -q http_host 'intent-recognition.fsticuffs.http-server.host' "${http_host}" \
       -q http_port 'intent-recognition.fsticuffs.http-server.port' "${http_port}" \
       -q intent_fst 'intent-recognition.fsticuffs.intent-fst' "${intent_fst}" \
       > "${var_file}"

    source "${var_file}"
fi

# -----------------------------------------------------------------------------

args=()

if [[ ! -z "${intent_fst}" ]]; then
    args+=('--intent-fst' "${intent_fst}")
fi

args+=("$@")

# -----------------------------------------------------------------------------
# Events FIFO
# -----------------------------------------------------------------------------

events_fifo="$(mktemp -u)"

function finish {
    rm -f "${events_fifo}"
}

trap finish EXIT
mkfifo "${events_fifo}"

# -----------------------------------------------------------------------------

python /http_server.py --host "${http_host}" --port "${http_port}" \
       < "${events_fifo}" | \
    python /main.py "${args[@]}" \
           > "${events_fifo}"
