#!/usr/bin/env bash

# -----------------------------------------------------------------------------
# Command-line Arguments
# -----------------------------------------------------------------------------

. "/shflags"

DEFINE_string 'profile' '' 'Path to profile directory' 'p'

DEFINE_string 'mqtt-host' '127.0.0.1' 'MQTT server address'
DEFINE_integer 'mqtt-port' 1883 'MQTT server port'

DEFINE_string 'recognize-intent' 'rhasspy/intent-recognition/recognize-intent' 'Topic for intent recognition request'
DEFINE_string 'intent-recognized' 'rhasspy/intent-recognition/intent-recognized' 'Topic for intent recognition response'

FLAGS "$@" || exit $?
eval set -- "${FLAGS_ARGV}"

# -----------------------------------------------------------------------------
# Default Settings
# -----------------------------------------------------------------------------

set -e

profile_dir="${FLAGS_profile}"

mqtt_host="${FLAGS_mqtt_host}"
mqtt_port="${FLAGS_mqtt_port}"

intent_fst=''

recognize_intent="${FLAGS_recognize_intent}"
intent_recognized="${FLAGS_intent_recognized}"

# -----------------------------------------------------------------------------
# Profile
# -----------------------------------------------------------------------------

if [[ ! -z "${profile_dir}" ]]; then
    profile_yml="${profile_dir}/profile.yml"

    var_file="$(mktemp)"
    function finish {
        rm -f "${var_file}"
    }

    trap finish EXIT

    export profile_dir
    yq "${profile_yml}" \
       -q mqtt_host 'mqtt.host' "${mqtt_host}" \
       -q mqtt_port 'mqtt.port' "${mqtt_port}" \
       -q intent_fst 'intent-recognition.fsticuffs.intent-fst' "${intent_fst}" \
       -q recognize_intent 'intent-recognition.mqtt-events.recognize-intent' "${recognize_intent}" \
       -q intent_recognized 'intent-recognition.mqtt-events.intent-recognized' "${intent_recognized}" \
       > "${var_file}"

    source "${var_file}"
fi

# -----------------------------------------------------------------------------

args=()

if [[ ! -z "${intent_fst}" ]]; then
    args+=('--intent-fst' "${intent_fst}")
fi

args+=("$@")

mosquitto_sub -h "${mqtt_host}" -p "${mqtt_port}" -t "${recognize_intent}" | \
    python /main.py "${args[@]}" | \
    mosquitto_pub -h "${mqtt_host}" -p "${mqtt_port}" -l -t "${intent_recognized}"
