#!/usr/bin/env python3
import os
import sys
import argparse
import re

import yaml
import pydash


def main():
    parser = argparse.ArgumentParser("yq")
    parser.add_argument("file", help="YAML file to load")
    parser.add_argument(
        "-q",
        "--query",
        action="append",
        nargs=3,
        help="Query with var name, path, default",
    )

    args = parser.parse_args()
    with open(args.file, "r") as yaml_file:
        yaml_dict = yaml.safe_load(yaml_file)

    if args.query:
        for var_name, query_path, query_default in args.query:
            query_value = pydash.get(yaml_dict, query_path, query_default)
            print(f"{var_name}='{query_value}'")


# -----------------------------------------------------------------------------

def env_constructor(loader, node):
    return os.path.expandvars(node.value)

yaml.SafeLoader.add_constructor("!env", env_constructor)

# -----------------------------------------------------------------------------

if __name__ == "__main__":
    main()
